version: '3'

services:
  jekyll:
    build: .
    command: npm run dev:jekyll
    ports:
      - "4000:4000"
      - "35729:35729"
    restart: always
    volumes:
      - ./src:/opt/src
      - ./output:/opt/output
